### PR TITLE
Disable first-run Google-sign in prompt.

### PR DESCRIPTION
**Pull request by Spirotot**

### CODE REVIEW

**Comment by thestinger** [comment]
If there's something broken about this due to the other changes it should probably be fixed rather than removed.

**Comment by Spirotot** [comment]
Hm, gotcha. When I use COS with GAPPS (building myself), Chromium will display a Google sign-in page on the first-run. For various reasons, the sign-in doesn't seem to work: hitting 'No Thanks' does nothing, and attempting to sign in ultimately fails (even if Chromium is granted the 'Contacts' permission).

Since I don't have any particular desire to log into Chromium with my Google ID, and those who do not have GAPPS installed can't even log in with a Google ID, I thought this might be an acceptable patch.

Totally understand if it's out-of-scope for COS mainline, though. I'll just continue using it in my own builds.

**Comment by thestinger** [comment]
Fixing it is in-scope so that this works properly with an official Google Play build, although I don't care about the hacked together aftermarket gapps bundles.

**Comment by thestinger** [comment]
I pushed a change to try:

https://github.com/CopperheadOS/chromium_patches/commit/b7e5da7ab0566f37b483fa0cb28db133f53e1aa0

**Comment by Spirotot** [comment]
I see. By "official Google Play" build, you're referring to using Chromium on the stock Nexus/Pixel ROMs? If so, then I agree: the sign-in page should **actually** be fixed, instead of just being commented out like I did...

**Comment by thestinger** [comment]
I think disabling the welcome page the way it was done was screwing up the page indexing.

**Comment by thestinger** [comment]
@Spirotot I'm referring to variants of CopperheadOS by commercial partners that may want to include Google Play, officially licensed from Google and included the proper way at build-time.

**Comment by Spirotot** [comment]
Sweet, I'll give that change a shot sometime soon! Thanks!

Regarding GPlay builds: gotcha!

**Pull request closed without merging**
